# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 
  cn: 表面科学与薄膜技术实验室
  en: Surface Science & Film Technology Lab
author:
  name: 郭兴伍 Xingwu Guo
  email: xingwuguo@sjtu.edu.cn

# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
_description: 
  cn: >-
    镁合金微弧氧化;
    铝合金快速阳极氧化;
    无电解槽阳极氧化及涂层修复技术;
    等离子体增强化学气相沉积 (PECVD);
    物理气相沉积 (PVD);
    气致变色薄膜;
    材料化学; 
    表面改性; 
    电化学;
    腐蚀与防护
  en: >-
    Magnesium Anodizing & PEO; 
    Aluminium Fast Anodizing; 
    Anodic Oxidation and Coating Repair Technology without Electrolytic Cell;
    PECVD;
    PVD;
    Gasochromic Film;
    Materiials Chemistry; 
    Surface Modification; 
    Electrochemistry;
    Corrosion and Protection
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xingwuguo.github.io" # the base hostname &bun protocol for your site, e.g. http://example.com
description: >-
              Dr. Xingwu Guo, Surface Science & Film Technology Lab, Light Alloy Net Forming National Engineering Research Center, School of Materials Science and Engineering, Shanghai Jiao Tong University (SJTU)
              郭兴伍 博士, 表面科学与薄膜技术实验室, 轻合金精密成型国家工程研究中心, 材料科学与工程学院, 上海交通大学
              1) 表面科学与薄膜技术
              主要研究轻金属材料 (Al、Mg、Ti) 表面自清洁(self-cleaning)、抗润湿 (anti-wetting)、耐腐蚀 (anti-corrosion) 以及耐摩擦磨损 (anti-wear) 等表面科学问题。重点针对不同的表面科学问题, 研究薄膜新材料制备技术, 服役过程中薄膜组织与性能的演变规律等, 从而为低成本高效制备性能优异的薄膜和表面改性膜层奠定理论基础和应用途径。所研究的铝合金和镁合金表面超声波微弧氧化技术 (PEO或MAO) 和物理气相沉积技术 (PVD) 已在我国的航空航天领域得到验证和应用。荣获中国有色工业技术科学奖二等奖1项; 国防科学技术奖二等奖1项; 上海市科学技术奖一等奖2项; 教育部技术发明奖二等奖1项。已先后发表SCI论文50余篇; 申请发明专利27项, 已获授权专利10项。
              2) 材料化学
              提出了材料表面成份和电位均匀化制备方法, 开展了室温离子液体中电沉积和镁合金材料表面成份和电位均匀化处理研究。在室温离子液体中利用电化学方法制备了高性能纳米多层膜和具有多级结构的微纳米多孔膜。解决了Mg-Li合金表面高耐腐蚀、高红外发射率和高导电性能薄膜制备的重大技术难题。发表离子液体电沉积金属薄膜方面的论文10余篇; 翻译出版材料化学专著一本, 申请发明专利一项。
              研究领域:
              等离子体辅助化学气相沉积 (PECVD),
              物理气相沉积 (PVD) 与离子束刻蚀 (IBE),
              有机/无机杂化涂层材料,
              高性能功能聚合物涂层 (例如 PI, PU, PTFE, PVDF等),
              纳米多孔功能聚合物薄膜,
              气致变色薄膜,
              电化学材料科学 (EMS),
              离子液体电沉积技术,
              轻金属材料 (Al, Mg, Ti) 表面改性与涂层技术,
              金属材料的腐蚀与防护,
              Research areas:
              Plasma enhanced chemical vapor deposition (PECVD),
              Physical vapor deposition (PVD) and ion beam etching (IBE),
              Organic/inorganic hybrid coating,
              High performance functional polymer coatings (e.g. PI, PU, PTFE, PVDF etc.),
              Nano porous functional polymer films,
              Gasochromic films,
              Electrochemical Materials Science (EMS),
              Ionic liquid electrodeposition,
              Surface modification and coating technologies fo light metallic materials (e.g. Al, Mg, Ti),
              Corrosion and protection of metallic materials,
              xingwuguo.github.io, GitHub
# github_username:  xingwuguo

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-email-protect
  - jekyll-multiple-languages-plugin
  - jekyll-seo-tag
  - jekyll-sitemap

languages: ["cn", "en"]
language_names:
  cn: 中文
  en: English version

include: ["_pages"]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
