# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 
  cn: 表面科学与薄膜技术实验室
  en: Surface Science & Film Technology Lab
author:
  name: 郭兴伍
  email: xingwuguo@sjtu.edu.cn
description: 
  cn: >-
    镁合金微弧氧化;
    铝合金快速阳极氧化;
    局部氧化及涂层修复技术;
    等离子体增强化学气相沉积 (PECVD);
    物理气相沉积 (PVD)
    气致变色薄膜; 
    表面改性; 
    电化学;
    腐蚀与防护
  en: >-
    Magnesium Anodizing & PEO; 
    Aluminium Fast Anodizing; 
    Material Chemistry; 
    PECVD;
    PVD;
    Photosensitive Resin; 
    Gas-induced Color Film; 
    Surface Modification; 
    Electrochemistry
    Corrosion and Protection
    
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xingwuguo.github.io" # the base hostname &bun protocol for your site, e.g. http://example.com
# github_username:  xingwuguo

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-email-protect
  - jekyll-multiple-languages-plugin
  - jekyll-seo-tag

languages: ["cn", "en"]
language_names:
  cn: 中文
  en: English version

include: ["_pages"]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
